version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./code:/code  # Vérifiez que ./code est bien le répertoire local contenant votre projet
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    container_name: php-container
    volumes:
      - ./code:/code  # Assurez-vous que PHP a aussi accès au même répertoire
